name: teste_postgres
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Gustavo Pacheco <gustavo@lojafacil.com.br>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
#  path: ^1.6.0
  postgres: ^2.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
