name: sale_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  hasura_connect: ^0.1.2
  sqflite: ^1.1.6+4
  dio: ^3.0.7
  rxdart: ^0.23.1
  bloc_pattern: ^2.5.1
  flutter_masked_text: ^0.8.0
  flutter_slidable: "^0.5.4"
  intl: ^0.16.0
  esys_flutter_share: ^1.0.2
  screenshot: ^0.1.1
  date_range_picker: ^1.0.6
  percent_indicator: "^2.1.1"
  rect_getter: 0.0.1
  flutter_circle_color_picker: ^0.1.1
  flutter_colorpicker: ^0.2.6
  cpf_cnpj_validator: ^1.0.5
  cached_network_image: ^2.0.0-rc
  amazon_cognito_identity_dart: ^0.0.22
  camera: ^0.5.7 
  path_provider:
  path:
  xml: ^3.5.0
  flutter_facebook_login: ^3.0.0
  shared_preferences: ^0.5.6
  device_id: ^0.2.0
  flutter_barcode_scanner: ^0.1.7
  firebase_messaging: ^6.0.9
  firebase_core: ^0.4.3+2
  firebase_analytics: ^5.0.9
  wifi: ^0.1.5
  ping_discover_network: ^0.2.0+1
  image: ^2.1.4
  esc_pos_printer: ^2.1.2
  flutter_echarts: ^1.2.0
  intercom_flutter: ^2.0.7
  auto_size_text: ^2.1.0
  dotted_border: ^1.0.4
  dynamic_widget: ^1.0.6
  google_fonts: ^0.3.9
  package_info: ^0.4.0+14
  version: ^1.0.3
  uuid: ^2.0.4
  device_info: ^0.4.2+1
  firebase_crashlytics: ^0.1.3+3
  logger: ^0.7.0
  logger_flutter: ^0.7.1
  common_files:
    path: ../common_files
  zendesk: ^1.0.2

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  intl_translation: ^0.17.1

flutter_icons:
  image_path: "assets/icon/icone_app.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/cadastroIcon.png
    - assets/caixaIcon.png
    - assets/estoqueIcon.png
    - assets/vendaIcon.png
    - assets/logoffIcon.png
    - assets/voltarIcon.png
    - assets/configuracaoIcon.png
    - assets/contaClienteIcon.png
    - assets/produtoIcon.png
    - assets/servicoIcon.png
    - assets/vendedorIcon.png
    - assets/clienteIcon.png
    - assets/lojaIcon.png
    - assets/ajustesIcon.png
    - assets/terminalIcon.png
    - assets/cupomIcon.png
    - assets/precoVendaIcon.png
    - assets/precoCustoIcon.png
    - assets/estoqueAtualIcon.png
    - assets/novoEstoqueIcon.png
    - assets/estoqueInputIcon.png
    - assets/gradeIcon.png
    - assets/varianteIcon.png
    - assets/transacaoIcon.png
    - assets/tipoPagamentoIcon.png
    - assets/userIcon.png
    - assets/dinheiroIcon.png
    - assets/servicoMiniIcon.png
    - assets/vendedorMiniIcon.png
    - assets/codBarrasIcon.png
    - assets/buscaIcon.png
    - assets/compartilharIcon.png
    - assets/trocaIcon.png
    - assets/reciboHeader.png
    - assets/vendaClienteIcon.png
    - assets/ticketMedioIcon.png
    - assets/zipcode.png
    - assets/mail.png
    - assets/postal.png
    - assets/postal1.png
    - assets/email-alert.png
    - assets/city-variant.png
    - assets/city-variant-outline.png
    - assets/box.png
    - assets/cesta.png
    - assets/price_tag.png
    - assets/price_tag_outline.png
    - assets/qrcode.png
    - assets/wallet.png
    - assets/dolarsign.png
    - assets/trashbin.png
    - assets/facebookLogo.png
    - assets/googleLogo.png
    - assets/animado.jpg
    - assets/classico.jpg
    - assets/mercadopago.png
    - assets/logomercadopago.png
    - assets/logomercadopagocinza.png
    - assets/logopicpay.png
    - assets/vendaConcluida.png
    - assets/deslizar.png
    - assets/setaPasso1.png
    - assets/setaTrilha.png
    - assets/setaCategoria.png
    - assets/setaAdicionarItem.png
    - assets/setaBaixoEsquerda.png
    - assets/reciboHeader.png
    - assets/descontoNaVendaIcon.png
    - assets/dashboardIcon.png
    - assets/suporteIcon.png
    - locales/PT_BR.json
    - locales/ES.json
    - locales/EN_US.json


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages